<a href="https://colab.research.google.com/github/obizoba/BIZI/blob/master/CA02_NUMBER_5_ASSIGNMENT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Regression Model for:
#CLUB SOCCER PREDITIONS(spi_matches_latest.csv)

In [20]:
import pandas as pd #we frist import all classes and liberies needed for our codes
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

#Uploading the data

In [21]:
data = pd.read_csv("spi_matches_latest.csv") #data is uploaded from system file.

In [23]:
matches = data #assgning a new name to the data.
matches.head(20) #showing first 19 rows of the data.

    season        date  league_id  ... nsxg2 adj_score1 adj_score2
0     2019  2019-03-01       1979  ...  0.54       1.05       0.00
1     2019  2019-03-01       1979  ...  1.50       0.00       3.26
2     2019  2019-03-01       1979  ...  0.75       3.15       0.00
3     2019  2019-03-01       1979  ...  0.94       0.00       1.05
4     2019  2019-03-01       1979  ...  2.08       2.10       2.10
5     2019  2019-03-02       1979  ...  1.72       2.61       1.05
6     2019  2019-03-02       1979  ...  1.98       1.05       1.05
7     2019  2019-03-03       1979  ...  0.41       2.61       2.10
8     2019  2019-03-08       1979  ...  0.89       1.05       0.00
9     2019  2019-03-08       1979  ...  0.53       2.10       2.10
10    2019  2019-03-08       1979  ...  2.61       0.00       3.68
11    2019  2019-03-09       1979  ...  1.06       3.15       2.10
12    2019  2019-03-09       1979  ...  2.11       3.15       3.15
13    2019  2019-03-10       1979  ...  1.70       1.05       0.00
14    2019  2019-03-10       1979  ...  0.62       1.68       1.05
15    2019  2019-03-10       1979  ...  0.89       1.05       2.10
16    2019  2019-03-29       1979  ...  1.88       3.99       3.15
17    2019  2019-03-30       1979  ...  1.72       0.00       1.05
18    2019  2019-03-30       1979  ...  1.07       0.00       1.05
19    2019  2019-03-30       1979  ...  0.57       1.05       2.10

[20 rows x 23 columns]

In [26]:
matches.shape#to show number os columns and rows in the dataset

(11676, 23)

In [28]:
matches.describe()#showing statistics of the data which are the mean,standard divation and quartile ranges.

             season     league_id  ...   adj_score1   adj_score2
count  11676.000000  11676.000000  ...  4999.000000  4999.000000
mean    2020.051387   2197.627355  ...     1.430486     1.230536
std        0.468372    938.435121  ...     1.202481     1.123228
min     2019.000000   1818.000000  ...     0.000000     0.000000
25%     2020.000000   1854.000000  ...     0.000000     0.000000
50%     2020.000000   1882.000000  ...     1.050000     1.050000
75%     2020.000000   2160.000000  ...     2.100000     2.100000
max     2021.000000   9541.000000  ...     8.090000    11.050000

[8 rows x 19 columns]

In [59]:
print(f"here are the last 10 rows of the data:\n {matches.tail(10)}")#showing last 10 rows of the data and seeing the null values of the data.

here are the last 10 rows of the data:
        season        date  league_id  ... nsxg2 adj_score1 adj_score2
11666    2021  2021-12-04       1947  ...   NaN        NaN        NaN
11667    2021  2021-12-04       1947  ...   NaN        NaN        NaN
11668    2021  2021-12-05       1874  ...   NaN        NaN        NaN
11669    2021  2021-12-05       1874  ...   NaN        NaN        NaN
11670    2021  2021-12-05       1874  ...   NaN        NaN        NaN
11671    2021  2021-12-05       1874  ...   NaN        NaN        NaN
11672    2021  2021-12-05       1874  ...   NaN        NaN        NaN
11673    2021  2021-12-05       1874  ...   NaN        NaN        NaN
11674    2021  2021-12-05       1874  ...   NaN        NaN        NaN
11675    2021  2021-12-05       1874  ...   NaN        NaN        NaN

[10 rows x 23 columns]

In [30]:
matches.skew()#showing how skew the data disribution is.

season         0.169739
league_id      4.720918
spi1           0.400114
spi2           0.402622
prob1          0.366154
prob2          0.636383
probtie       -1.242871
proj_score1    1.046911
proj_score2    0.902534
importance1    0.796717
importance2    0.835669
score1         0.973628
score2         1.145759
xg1            1.031679
xg2            1.128469
nsxg1          1.026148
nsxg2          1.413436
adj_score1     0.806226
adj_score2     0.996224
dtype: float64

In [62]:
features = matches.iloc[:,]#selecting features.
print(f"we can view the data features for the first 10 rows:\n{features.head(10)}")#showing the festures of the first 10 rows.
features.head(10)#to help have a larger view of the data.

we can view the data features for the first 10 rows:
   season        date  league_id  ... nsxg2 adj_score1 adj_score2
0    2019  2019-03-01       1979  ...  0.54       1.05       0.00
1    2019  2019-03-01       1979  ...  1.50       0.00       3.26
2    2019  2019-03-01       1979  ...  0.75       3.15       0.00
3    2019  2019-03-01       1979  ...  0.94       0.00       1.05
4    2019  2019-03-01       1979  ...  2.08       2.10       2.10
5    2019  2019-03-02       1979  ...  1.72       2.61       1.05
6    2019  2019-03-02       1979  ...  1.98       1.05       1.05
7    2019  2019-03-03       1979  ...  0.41       2.61       2.10
8    2019  2019-03-08       1979  ...  0.89       1.05       0.00
9    2019  2019-03-08       1979  ...  0.53       2.10       2.10

[10 rows x 23 columns]

   season        date  league_id  ... nsxg2 adj_score1 adj_score2
0    2019  2019-03-01       1979  ...  0.54       1.05       0.00
1    2019  2019-03-01       1979  ...  1.50       0.00       3.26
2    2019  2019-03-01       1979  ...  0.75       3.15       0.00
3    2019  2019-03-01       1979  ...  0.94       0.00       1.05
4    2019  2019-03-01       1979  ...  2.08       2.10       2.10
5    2019  2019-03-02       1979  ...  1.72       2.61       1.05
6    2019  2019-03-02       1979  ...  1.98       1.05       1.05
7    2019  2019-03-03       1979  ...  0.41       2.61       2.10
8    2019  2019-03-08       1979  ...  0.89       1.05       0.00
9    2019  2019-03-08       1979  ...  0.53       2.10       2.10

[10 rows x 23 columns]

In [63]:
print(f"here is the datae type:\n{matches.dtypes}")

here is the datae type:
season           int64
date            object
league_id        int64
league          object
team1           object
team2           object
spi1           float64
spi2           float64
prob1          float64
prob2          float64
probtie        float64
proj_score1    float64
proj_score2    float64
importance1    float64
importance2    float64
score1         float64
score2         float64
xg1            float64
xg2            float64
nsxg1          float64
nsxg2          float64
adj_score1     float64
adj_score2     float64
dtype: object

season           int64
date            object
league_id        int64
league          object
team1           object
team2           object
spi1           float64
spi2           float64
prob1          float64
prob2          float64
probtie        float64
proj_score1    float64
proj_score2    float64
importance1    float64
importance2    float64
score1         float64
score2         float64
xg1            float64
xg2            float64
nsxg1          float64
nsxg2          float64
adj_score1     float64
adj_score2     float64
dtype: object